name: "Rest-Auth CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      JWT_SECRET: test_jwt_secrer
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.11.3"
      
      - name: Install Python Packages
        working-directory: ./registration
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
      - name: Run Tests
        run: python -m unittest discover -v -s './tests' -p 'test_*.py'    
        
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub 
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Build and Push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:latest
          
      - name: Run Docker Compose
        run: docker-compose up -d
